package org.dungeon.help;

// Generated by IDEA.
public class AspectHelpBuilder {
    private String name;
    private String info;
    private String[] aliases;

    public AspectHelpBuilder setName(String name) {
        this.name = name;
        return this;
    }

    public AspectHelpBuilder setInfo(String info) {
        this.info = info;
        return this;
    }

    public AspectHelpBuilder setAliases(String[] aliases) {
        this.aliases = aliases;
        return this;
    }

    public AspectHelp createAspectHelp() {
        return new AspectHelp(name, info, aliases);
    }
}